logging:
  level:
    root: INFO
  file:
    path: log
server:
  port: 18411
  servlet:
    context-path: /jxyz-etl
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz-etl
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbif49m6k7l651e5fo.mysql.zhangbei.rds.aliyuncs.com:3306/dcp_business?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: Liqin1988
    hikari:
      connection-timeout: 15000
      auto-commit: true
      max-lifetime: 600000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15

jxyz:
  #每页最大条数
  data_total: 10000
  #数据库名称
  table_schema: jxyz
  data_base_path: /temp/etl
  #文件上传地址
  upload_url: https://112.51.254.102:18443/premiseapi/api/file/upload
  #文件传输地址code
#  file_code_url: http://161.117.39.189:45678/jxyzadoetl/etl/download/
  file_code_url: http://127.0.0.1:45678/jxyzadoetl/etl/download/
#  获取ado数据地址
  get_user_data_url: http://localhost:45678/jxyzadoetl/etl/syncDwrResources
  
  get_token:
    user_name: sn_baby
    password: Baby@1988
    token_url: https://112.51.254.102:18443/iam/keystone/auth/getToken
    
  ado:
    user_name: sn_baby
    password: Baby@1988
    token_url: https://112.51.254.102:18443/iam/keystone/auth/getToken
    qry_url: http://127.0.0.1:45678/jxyzadoetl/etl/qry
    ins_url: http://127.0.0.1:45678/jxyzadoetl/etl/ins
    

  #定义需要调用的http数据转移接口地址
#  url: http://localhost:9001/jxyzwg/dataSynch/dataSynchronization
