logging:
  level:
    root: INFO
  file:
    path: log
server:
  port: 9002
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz-etl
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.102.229:3306/jxyz_test?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root@1234
    hikari:
      connection-timeout: 15000
      auto-commit: true
      max-lifetime: 600000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15
#jxyz:
#  created_user: 王小贱
#  minio_data_base_path: /home/minio/data
#  upzip_base_path: /home/unzip
#  default_year: 2020