logging:
  level:
    root: INFO
  file:
    path: log
server:
  port: 10000
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz-sun
  rabbitmq:
    host: 161.117.39.189
    port: 5672
    username: jxyz_ado
    password: HdIdh2_J4SMId2
    
jxyz:
  rabbitmq:
    exchange: fanout-exchange-sun