logging:
  level:
    root: INFO
  file:
    path: log
server:
  port: 10002
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz-venus
  rabbitmq:
    host: 161.117.39.189
    port: 5672
    username: jxyz_ado
    password: HdIdh2_J4SMId2
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.32.115:3306/jxyz?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1qaz@WSX
    hikari:
      connection-timeout: 15000
      auto-commit: true
      max-lifetime: 600000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15
  redis:
    host: 161.117.39.189
    port: 6379
    database: 0
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
  cache:
    redis:
      time-to-live: -1 #毫秒

jxyz:
  rabbitmq:
    exchange: fanout-exchange-sun
    queue: sun.venus
    err-exchange: fanout-exchange-sun-venus-err
    err-queue: sun.venus.err