logging:
  level:
    root: INFO
  file:
    path: log
server:
  port: 18409
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz-salary
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jxyz?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: jxyz
    password: jxyz@1234
    hikari:
      connection-timeout: 15000
      auto-commit: true
      max-lifetime: 600000
      pool-name: DatebookHikariCP
      minimum-idle: 30
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 30
  task:
    execution:
      pool:
        core-size: 16
        keep-alive: 3s
      thread-name-prefix: salary-thread-
  
jxyz:
  etl:
    download_url: http://127.0.0.1:18411/jxyz-etl/etl/download
    upload_url: http://127.0.0.1:18411/jxyz-etl/etl/upload