logging:
  level:
    root: INFO
  file:
    path: log
server:
  port: 18412
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz
  rabbitmq:
    host: 127.0.0.1
    port: 18416
    username: jxyz_ado
    password: HdIdh2_J4SMId2
      
jxyz:
  created_user: 王小贱
  minio_data_base_path: /home/minio/data
  upzip_base_path: /home/unzip
  default_year: 2020
  datasource:
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jxyz?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: jxyz
      password: jxyz@1234
      hikari:
        connection-timeout: 15000
        auto-commit: true
        max-lifetime: 600000
        pool-name: MasterDatebookHikariCP
        minimum-idle: 5
        connection-test-query: SELECT 1
        idle-timeout: 30000
        maximum-pool-size: 15
    slave:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/jxyz?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
      username: jxyz
      password: jxyz@1234
      hikari:
        connection-timeout: 15000
        auto-commit: true
        max-lifetime: 600000
        pool-name: SlaveDatebookHikariCP
        minimum-idle: 5
        connection-test-query: SELECT 1
        idle-timeout: 30000
        maximum-pool-size: 15
